#!/usr/bin/env python
"""--------------------------------------------------------------------
COPYRIGHT 2018 Stanley Innovation Inc.

Software License Agreement:

The software supplied herewith by Stanley Innovation Inc. (the "Company") 
for its licensed Segway RMP Robotic Platforms is intended and supplied to you, 
the Company's customer, for use solely and exclusively with Stanley Innovation 
products. The software is owned by the Company and/or its supplier, and is 
protected under applicable copyright laws.  All rights are reserved. Any use in 
violation of the foregoing restrictions may subject the user to criminal 
sanctions under applicable laws, as well as to civil liability for the 
breach of the terms and conditions of this license. The Company may 
immediately terminate this Agreement upon your use of the software with 
any products that are not Stanley Innovation products.

The software was written using Python programming language.  Your use 
of the software is therefore subject to the terms and conditions of the 
OSI- approved open source license viewable at http://www.python.org/.  
You are solely responsible for ensuring your compliance with the Python 
open source license.

You shall indemnify, defend and hold the Company harmless from any claims, 
demands, liabilities or expenses, including reasonable attorneys fees, incurred 
by the Company as a result of any claim or proceeding against the Company 
arising out of or based upon: 

(i) The combination, operation or use of the software by you with any hardware, 
    products, programs or data not supplied or approved in writing by the Company, 
    if such claim or proceeding would have been avoided but for such combination, 
    operation or use.
 
(ii) The modification of the software by or on behalf of you 

(iii) Your use of the software.

 THIS SOFTWARE IS PROVIDED IN AN "AS IS" CONDITION. NO WARRANTIES,
 WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 
 \file   sim_odometry

 \brief  Simulates odometry from ground truth

 \Platform: Linux/ROS Kinetic
--------------------------------------------------------------------"""
from nav_msgs.msg import Odometry
from geometry_msgs.msg import Twist
import tf
import rospy
import math

class SimOdometry:
    def __init__(self):
        self._OdomData = Odometry()
        self._OdomPub = rospy.Publisher("/segway/odometry/local_filtered", Odometry, queue_size=100)
        self._OdomPub2 = rospy.Publisher("/segway/feedback/wheel_odometry", Odometry, queue_size=100)
        
        self._OdomData.header.frame_id = 'odom'
        self._OdomData.child_frame_id  = 'base_link'
        
        
        self._OdomData.pose.covariance = [0.00017,0.0,0.0,0.0,0.0,0.0,
                                          0.0,0.00017,0.0,0.0,0.0,0.0,
                                          0.0,0.0,0.00017,0.0,0.0,0.0,
                                          0.0,0.0,0.0,0.00000,0.0,0.0,
                                          0.0,0.0,0.0,0.0,0.00000,0.0,
                                          0.0,0.0,0.0,0.0,0.0,0.00017]
             
        self._OdomData.twist.covariance = [0.00017,0.0,0.0,0.0,0.0,0.0,
                                           0.0,0.00017,0.0,0.0,0.0,0.0,
                                           0.0,0.0,0.00017,0.0,0.0,0.0,
                                           0.0,0.0,0.0,0.00000,0.0,0.0,
                                           0.0,0.0,0.0,0.0,0.00000,0.0,
                                           0.0,0.0,0.0,0.0,0.0,0.00017]
                                           
        self._vel_sign = 1.0
        rospy.Subscriber("/ground_truth_odom",Odometry,self._publish_odom_tf)
        rospy.Subscriber("/diff_vel_controller/cmd_vel",Twist,self._update_vel)
    
    def _update_vel(self,cmd):
    
        self._vel_sign = math.copysign(self._vel_sign,cmd.linear.x)
    
    def _publish_odom_tf(self,msg):
    
        (r, p, y) = tf.transformations.euler_from_quaternion([msg.pose.pose.orientation.x,
                                                              msg.pose.pose.orientation.y,
                                                              msg.pose.pose.orientation.z,
                                                              msg.pose.pose.orientation.w])
        rot = tf.transformations.quaternion_from_euler(0, 0, y)
        
        
        self._OdomData.pose.pose.orientation.x=rot[0]
        self._OdomData.pose.pose.orientation.y=rot[1]
        self._OdomData.pose.pose.orientation.z=rot[2]
        self._OdomData.pose.pose.orientation.w=rot[3]
        
        self._OdomData.pose.pose.position.x = msg.pose.pose.position.x
        self._OdomData.pose.pose.position.y = msg.pose.pose.position.y
        self._OdomData.pose.pose.position.z = 0.0
        
        self._OdomData.header.stamp = msg.header.stamp
        self._OdomData.header.seq = msg.header.seq
        
        tmp = math.sqrt(math.pow(msg.twist.twist.linear.x,2)+math.pow(msg.twist.twist.linear.y,2)) * self._vel_sign
        
        self._OdomData.twist.twist.linear.x = tmp
        self._OdomData.twist.twist.linear.y = 0.0
        self._OdomData.twist.twist.linear.z = 0.0
        self._OdomData.twist.twist.angular.x = 0.0
        self._OdomData.twist.twist.angular.y = 0.0
        self._OdomData.twist.twist.angular.z = msg.twist.twist.angular.z
        
        x = self._OdomData.pose.pose.position.x
        y = self._OdomData.pose.pose.position.y
        z = self._OdomData.pose.pose.position.z
        
        rot[0] = msg.pose.pose.orientation.x
        rot[1] = msg.pose.pose.orientation.y
        rot[2] = msg.pose.pose.orientation.z
        rot[3] = msg.pose.pose.orientation.w
        
        
        self._OdomPub.publish(self._OdomData)
        self._OdomPub2.publish(self._OdomData)
        
        br = tf.TransformBroadcaster()
        br.sendTransform((x, y, z),
                          rot,
                          msg.header.stamp,
                          "base_link",
                          "odom")
        

if __name__ == "__main__":
    """
    Initialize the node
    """
    rospy.init_node('sim_odometry')
    SimOdometry()
    rospy.spin()
    
