#!/usr/bin/env python
"""--------------------------------------------------------------------
COPYRIGHT 2016 Stanley Innovation Inc.

Software License Agreement:

The software supplied herewith by Stanley Innovation Inc. (the "Company") 
for its licensed SI Vector Platform is intended and supplied to you, 
the Company's customer, for use solely and exclusively with Stanley Innovation 
products. The software is owned by the Company and/or its supplier, and is 
protected under applicable copyright laws.  All rights are reserved. Any use in 
violation of the foregoing restrictions may subject the user to criminal 
sanctions under applicable laws, as well as to civil liability for the 
breach of the terms and conditions of this license. The Company may 
immediately terminate this Agreement upon your use of the software with 
any products that are not Stanley Innovation products.

The software was written using Python programming language.  Your use 
of the software is therefore subject to the terms and conditions of the 
OSI- approved open source license viewable at http://www.python.org/.  
You are solely responsible for ensuring your compliance with the Python 
open source license.

You shall indemnify, defend and hold the Company harmless from any claims, 
demands, liabilities or expenses, including reasonable attorneys fees, incurred 
by the Company as a result of any claim or proceeding against the Company 
arising out of or based upon: 

(i) The combination, operation or use of the software by you with any hardware, 
    products, programs or data not supplied or approved in writing by the Company, 
    if such claim or proceeding would have been avoided but for such combination, 
    operation or use.
 
(ii) The modification of the software by or on behalf of you 

(iii) Your use of the software.

 THIS SOFTWARE IS PROVIDED IN AN "AS IS" CONDITION. NO WARRANTIES,
 WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 
 \file   init_sim.py

 \brief  This node serves to setup simulation 

 \Platform: Linux/ROS Indigo
--------------------------------------------------------------------"""
import rospy
from std_msgs.msg import Bool
from moveit_python import MoveGroupInterface
from moveit_msgs.msg import MoveItErrorCodes
from kinova_action_clients.gripper_action_client import GripperActionClient

if __name__ == "__main__":
    rospy.init_node('init_robots')

    # Do we move the arm to home and tuck at startup?
    # Currently false since the arm sometimes hits the case...
    init_arm = True
    
    home_pub = rospy.Publisher('/segway/home_arms', Bool, queue_size=1000)
    home_arm = Bool()
    home_arm.data = True
    move_group = MoveGroupInterface("right_arm","base_link")
    move_group.setPlannerId("RRTConnectkConfigDefault")
    rgripper = GripperActionClient('right')
    
    right_arm_joints = ["right_elbow_joint",
                        "right_shoulder_lift_joint",
                        "right_shoulder_pan_joint",
                        "right_wrist_1_joint",
                        "right_wrist_2_joint",
                        "right_wrist_3_joint"]
   
    # This is a hardware so need to adjust gripper parameters
    gripper_closed = 0.0
    gripper_open = 0.165

    homed = [1.764,0.0833,1.482,2.042,-1.463,1.880]
    tucked = [2.6,2.238,1.6225,0.2417,-0.6559,1.7261]
    success=False

    if init_arm:
        while not rospy.is_shutdown() and not success:
            result = move_group.moveToJointPosition(right_arm_joints, homed, 0.05)
            if result.error_code.val == MoveItErrorCodes.SUCCESS:
                success=True   

        rgripper.command(gripper_open,block=True)
        rospy.sleep(2.0)

        success = False
        while not success and not rospy.is_shutdown():
            home_pub.publish(home_arm)
            try:
                res = rospy.wait_for_message('/segway/arms_are_homed', Bool, timeout=20.0)
                success = res.data
            except:
               success = False        
            
        rgripper.command(gripper_closed,block=True)
    
        success=False
        while not rospy.is_shutdown() and not success:
            result = move_group.moveToJointPosition(right_arm_joints, tucked, 0.05)
            if result.error_code.val == MoveItErrorCodes.SUCCESS:
                success=True
            
        rgripper.command(gripper_closed,block=True)
